spring:
  application:
    name: authentication-authorization-service
  mongodb:
    host: localhost
    port: 27017
jwt:
  private-key: classpath:keys/private.pem
  public-key: classpath:keys/public.pem
