spring:
  application:
    name: authentication-authorization-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:auth_db}?useSSL=true&allowPublicKeyRetrieval=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    # HikariCP Connection Pooling (Crucial for production performance)
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
    # Disable for better memory management
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
jwt:
  private-key: ${PRIVATE_KEY}
  public-key: ${PUBLIC_KEY}
